# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import post_office.validators
import subscribe_form._db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formemailtemplate',
            options={'verbose_name': 'Form email template', 'verbose_name_plural': 'Form email templates'},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='bcc',
            field=subscribe_form._db_fields.CommaSeparatedEmailField(blank=True, verbose_name='Bcc'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='cc',
            field=subscribe_form._db_fields.CommaSeparatedEmailField(blank=True, verbose_name='Cc'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(blank=True, help_text='If empty - use settings.DEFAULT_FROM_EMAIL', max_length=254, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='to',
            field=subscribe_form._db_fields.CommaSeparatedEmailField(blank=True, verbose_name='Email To'),
        ),
        migrations.AlterField(
            model_name='emailtemplateattachment',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='subscribe_form.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
